spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jackson:
    date-format: com.microsoft.azure.simpletodo.configuration.RFC3339DateFormat
    serialization: 
      write-dates-as-timestamps: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
