spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jackson:
    date-format: com.microsoft.azure.simpletodo.configuration.RFC3339DateFormat
    serialization: 
      write-dates-as-timestamps: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
