spring:
  jackson:
    date-format: com.microsoft.azure.simpletodo.configuration.RFC3339DateFormat
    serialization: WRITE_DATES_AS_TIMESTAMPS=false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
